definitions:
  github.com_Coflnet_tem-backend_internal_api.PlayerResponse:
    properties:
      generic_items:
        items: {}
        type: array
      generic_pets:
        items:
          type: string
        type: array
      id:
        $ref: '#/definitions/mongo.PlayerId'
      items:
        items: {}
        type: array
      pets:
        items:
          $ref: '#/definitions/mongo.Pet'
        type: array
    type: object
  internal_api.PlayerResponse:
    properties:
      generic_items:
        items: {}
        type: array
      generic_pets:
        items:
          type: string
        type: array
      id:
        $ref: '#/definitions/mongo.PlayerId'
      items:
        items: {}
        type: array
      pets:
        items:
          $ref: '#/definitions/mongo.Pet'
        type: array
    type: object
  mongo.Owner:
    properties:
      player_uuid:
        type: string
      profile_uuid:
        type: string
    type: object
  mongo.Pet:
    properties:
      candy:
        type: integer
      current_owner:
        $ref: '#/definitions/mongo.Owner'
      held_item:
        type: string
      id:
        type: string
      last_checked:
        type: string
      level:
        type: integer
      location:
        type: string
      name:
        type: string
      previous_owner:
        $ref: '#/definitions/mongo.Owner'
      rarity:
        type: string
      skin:
        type: string
      start:
        type: string
    type: object
  mongo.PlayerId:
    type: object
info:
  contact: {}
paths:
  /player/{uuid}:
    get:
      consumes:
      - application/json
      description: get a player by his player uuid
      parameters:
      - description: uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_api.PlayerResponse'
      summary: PlayerUUID
      tags:
      - player
swagger: "2.0"
